import ProjectDescription

let workspace = Workspace(
    name: "ButtonHeist",
    projects: [
        ".",
        "TestApp",
    ],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
